"""
Control command data structures.

This module defines lightweight data containers that represent commands
generated by the controller and sent to the actuator layer.

These command objects represent *intent*, not hardware details.
They are intentionally simple, explicit, and serial-agnostic.

The controller outputs:
- DriveCommand: how the robot base should move
- MechanismCommand: desired positions or modes for non-drive actuators
"""

from dataclasses import dataclass
from enum import Enum
from typing import Optional


# ============================================================
# Drive (base motion)
# ============================================================

@dataclass
class DriveCommand:
    """
    High-level drive command.

    Attributes:
        linear: Forward/backward command.
                Units must be consistent across the system (e.g. m/s).
        angular: Rotation command.
                 Units must be consistent (e.g. deg/s or rad/s).
    """
    linear: float = 0.0
    angular: float = 0.0


# Pre-made stop command for convenience and safety
DRIVE_STOP = DriveCommand(0.0, 0.0)


# ============================================================
# Mechanisms (non-drive actuators)
# ============================================================

class MechMotorMode(str, Enum):
    """
    Control mode for a mechanism DC motor.

    DUTY:
        Open-loop duty cycle command in range [-1, 1]

    POS_DEG:
        Closed-loop position command in degrees
        (Arduino is expected to run the control loop)

    RPM:
        Closed-loop speed command in RPM
    """
    DUTY = "DUTY"
    POS_DEG = "POS_DEG"
    RPM = "RPM"


@dataclass
class MechMotorCommand:
    """
    Command for a single mechanism DC motor.

    Attributes:
        mode: How the motor should be controlled.
        value: Setpoint value corresponding to the selected mode.
    """
    mode: MechMotorMode
    value: float


@dataclass
class MechanismCommand:
    """
    High-level mechanism command.

    This represents desired actuator setpoints, not low-level signals.
    Fields may be left as None to indicate "no change".

    Typical usage:
    - Servos: absolute angle setpoints in degrees
    - DC motors: position (deg), speed (RPM), or duty commands
    """

    # 2 Mechanism Motors (deg)
    motor_RHS: Optional[MechMotorCommand] = None
    motor_LHS: Optional[MechMotorCommand] = None

    # two servos (deg)
    servo_LID_deg: Optional[float] = None
    servo_SWEEP_deg: Optional[float] = None


# No-op for this robot means:
# - LHS motor actively held at 0 deg (belt-driven, back-drivable)
# - RHS motor untouched (worm gear holds)
# - Servos untouched
MECH_NOOP = MechanismCommand(
    motor_LHS=MechMotorCommand(MechMotorMode.POS_DEG, 0.0)
)



