"""
Control command data structures.

This module defines lightweight data containers that represent commands
generated by the controller and sent to the drive system (and later,
mechanisms). These command objects are intentionally simple and explicit
to make the interface between high-level control logic and low-level
hardware control clear and safe.

Currently this module defines drive motion commands only, but it is
designed to be extended in the future to include mechanism or actuator
commands as the robot's capabilities grow.
"""
"""
Control command data structures.

This module defines lightweight command objects produced by the high-level
Controller and consumed by the drive/hardware layer (Arduino interface,
drive controller, etc.).

These objects are intentionally simple and explicit:
- They are easy to serialize/log
- They keep control decisions separate from hardware implementation
- They provide a stable interface as the project grows

No hardware code or state machine logic should live in this file.
"""

from dataclasses import dataclass



@dataclass
class DriveCommand:
    """
    High-level drive command.

    Attributes:
        linear: Forward/backward command (units are whatever your system uses,
                but stay consistent. Common choices are normalized -1..1 or m/s).
        angular: Rotation command (common choices are normalized -1..1 or rad/s).
    """
    linear: float = 0.0
    angular: float = 0.0


# Pre-make a stop drive command
DRIVE_STOP = DriveCommand(0.0, 0.0)
